import { callEcsOpenApi, deleteEcsServers, getEcsJob, getEcsServer, listEcsAvailabilityZones, listEcsFlavors, listEcsServers, rebootEcsServers, startEcsServers, stopEcsServers } from "../openapi";
import { generatedEcsOperations } from "../generated-operations";
import type { SubMcp } from "./types";

export const subMcp: SubMcp = {
  id: "ecs",
  title: "Elastic Cloud Server (ECS)",
  description: "ECS OpenAPI child MCP. Operations are sourced from the ECS API Explorer.",
  sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=NovaListVersions",
  operations: [
    { id: "openapi_request", description: "Call another ECS API Explorer endpoint through the ECS child MCP. Use an API path such as /v1/{project_id}/... and optional query/body; non-GET/HEAD methods require explicit user confirmation.", isReadOnly: false, requiresConfirmation: (input) => input.method !== "GET" && input.method !== "HEAD", inputSchema: { type: "object", properties: { method: { type: "string", enum: ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE"] }, path: { type: "string" }, query: { type: "object" }, body: {}, maxResponseBytes: { type: "integer", minimum: 1, maximum: 1048576 }, region: { type: "string" }, projectId: { type: "string" } }, required: ["method", "path"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=NovaListVersions", execute: callEcsOpenApi },
    { id: "list_servers", description: "List ECS server details in one project.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, limit: { type: "number", minimum: 1, maximum: 1000 }, name: { type: "string" }, status: { type: "string" } } }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=ListServersDetails", execute: listEcsServers },
    { id: "get_server", description: "Get the details of one ECS server.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, serverId: { type: "string" } }, required: ["serverId"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=ShowServer", execute: getEcsServer },
    { id: "get_job", description: "Get the status of an asynchronous ECS job returned by lifecycle operations.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, jobId: { type: "string" } }, required: ["jobId"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=ShowJob", execute: getEcsJob },
    { id: "list_availability_zones", description: "List ECS availability zones and their availability state in one project.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" } } }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=ListServerAzInfo", execute: listEcsAvailabilityZones },
    { id: "list_flavors", description: "List ECS flavor details and extended information, optionally filtered by availability zone.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, availabilityZone: { type: "string" }, limit: { type: "integer", minimum: 1, maximum: 1000 }, marker: { type: "string" } } }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=ListFlavors", execute: listEcsFlavors },
    { id: "start_servers", description: "Start up to 1,000 ECS servers asynchronously. This operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, serverIds: { type: "array", minItems: 1, maxItems: 1000, items: { type: "string" } } }, required: ["serverIds"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=BatchStartServers", execute: startEcsServers },
    { id: "stop_servers", description: "Stop up to 1,000 ECS servers asynchronously. The default type is SOFT; this operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, serverIds: { type: "array", minItems: 1, maxItems: 1000, items: { type: "string" } }, type: { type: "string", enum: ["SOFT", "HARD"] } }, required: ["serverIds"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=BatchStopServers", execute: stopEcsServers },
    { id: "reboot_servers", description: "Reboot up to 1,000 ECS servers asynchronously. Select SOFT or HARD and explicitly confirm before execution.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, serverIds: { type: "array", minItems: 1, maxItems: 1000, items: { type: "string" } }, type: { type: "string", enum: ["SOFT", "HARD"] } }, required: ["serverIds", "type"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=BatchRebootServers", execute: rebootEcsServers },
    { id: "delete_servers", description: "Delete up to 1,000 pay-per-use ECS servers asynchronously. EIPs and data disks are preserved by default; explicitly set deletion flags only after user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, projectId: { type: "string" }, serverIds: { type: "array", minItems: 1, maxItems: 1000, items: { type: "string" } }, deletePublicIp: { type: "boolean" }, deleteVolume: { type: "boolean" } }, required: ["serverIds"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/doc?api=DeleteServers", execute: deleteEcsServers },
    ...generatedEcsOperations(),
  ],
};
