import { appendObsObject, copyObsObject, createObsBucket, deleteObsBucket, deleteObsObject, getObsBucketLocation, getObsBucketMetadata, getObsObject, getObsObjectMetadata, listObsBuckets, listObsObjects, putObsObject } from "../openapi";
import type { SubMcp } from "./types";

export const subMcp: SubMcp = {
  id: "obs",
  title: "Object Storage Service (OBS)",
  description: "OBS OpenAPI child MCP. Operations are sourced from the OBS API Explorer.",
  sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=AppendObject",
  operations: [
    { id: "list_buckets", description: "List all OBS buckets available to the authenticated account.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" } } }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=ListBuckets", execute: listObsBuckets },
    { id: "get_bucket_metadata", description: "Get OBS bucket metadata without modifying the bucket.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" } }, required: ["bucket"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=GetBucketMetadata", execute: getObsBucketMetadata },
    { id: "get_bucket_location", description: "Get the region where one OBS bucket resides.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" } }, required: ["bucket"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=GetBucketLocation", execute: getObsBucketLocation },
    { id: "list_objects", description: "List up to 1,000 objects in one OBS bucket.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" }, prefix: { type: "string" }, marker: { type: "string" }, delimiter: { type: "string" }, maxKeys: { type: "number", minimum: 1, maximum: 1000 } }, required: ["bucket"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=ListObjects", execute: listObsObjects },
    { id: "get_object_metadata", description: "Get OBS object metadata without downloading the object content.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" }, key: { type: "string" }, versionId: { type: "string" } }, required: ["bucket", "key"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=HeadObject", execute: getObsObjectMetadata },
    { id: "get_object", description: "Read up to maxBytes from the start of one OBS object and return it as base64.", isReadOnly: true, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" }, key: { type: "string" }, versionId: { type: "string" }, maxBytes: { type: "integer", minimum: 1, maximum: 1048576 } }, required: ["bucket", "key", "maxBytes"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=GetObject", execute: getObsObject },
    { id: "create_bucket", description: "Create an OBS bucket in the selected region. This operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" } }, required: ["bucket"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=CreateBucket", execute: createObsBucket },
    { id: "put_object", description: "Upload base64-encoded content as one OBS object. This operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" }, key: { type: "string" }, contentBase64: { type: "string", format: "base64" }, contentType: { type: "string" } }, required: ["bucket", "key", "contentBase64"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=PutObject", execute: putObsObject },
    { id: "copy_object", description: "Create one server-side copy of an OBS object. This operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" }, key: { type: "string" }, sourceBucket: { type: "string" }, sourceKey: { type: "string" }, sourceVersionId: { type: "string" } }, required: ["bucket", "key", "sourceBucket", "sourceKey"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=CopyObject", execute: copyObsObject },
    { id: "append_object", description: "Append base64-encoded content to an OBS appendable object at an explicit byte position. This operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" }, key: { type: "string" }, position: { type: "integer", minimum: 0 }, contentBase64: { type: "string", format: "base64" }, contentType: { type: "string" } }, required: ["bucket", "key", "position", "contentBase64"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=AppendObject", execute: appendObsObject },
    { id: "delete_object", description: "Delete one OBS object or one object version. This operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" }, key: { type: "string" }, versionId: { type: "string" } }, required: ["bucket", "key"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=DeleteObject", execute: deleteObsObject },
    { id: "delete_bucket", description: "Delete one empty OBS bucket. This operation always requires explicit user confirmation.", isReadOnly: false, inputSchema: { type: "object", properties: { region: { type: "string" }, bucket: { type: "string" } }, required: ["bucket"] }, sourceUrl: "https://console.huaweicloud.com/apiexplorer/#/openapi/OBS/doc?api=DeleteBucket", execute: deleteObsBucket },
  ],
};
